#数据源配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://39.105.43.204:3306/yzinterface
    username: yzinterface
    password: yzinterface
    driver-class-name: com.mysql.jdbc.Driver

#MyBaris配置
mybatis:
  #实体类路径
  type-aliases-package: classpath:cn/wzzm/order/pojo
  #Mapper文件路径
  mapper-locations: classpath:cn/wzzm/order/dao/*.xml

#服务器配置
name: order
server:
  #端口配置
  port: 8081
